version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: wwebjs-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: wwebjs_admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d wwebjs_admin"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: